spring:
  application:
    name: client-user
  redis:
    database: 2
    host: 192.168.10.83
    port: 6379
#    password: 1qaz@WSX
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms
server:
  port: 18000
  servlet:
    context-path: /client-user

security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:18001/oauth/authorize
      access-token-uri: http://localhost:18001/oauth/token
    resource:
      jwt:
        key-uri: http://localhost:18001/oauth/token_key
        key-value: dev
    authorization:
      check-token-access: http://localhost:18001/oauth/check_token